let validFileExtensions = {
  'c': true,
  'cc' : true,
  'class': true,
  'clj': true,
  'cpp': true,
  'cs': true,
  'cxx': true,
  'el': true,
  'go': true,
  'java': true,
  'lua': true,
  'm': true,
  'm4': true,
  'md': true,
  'php': true,
  'pl': true,
  'po': true,
  'py': true,
  'rb': true,
  'rs': true,
  'sh': true,
  'swift': true,
  'vb': true,
  'vcxproj': true,
  'xcodeproj': true,
  'xml': true,
  'diff': true,
  'patch': true,
  'html': true,
  'htm': true,
  'css': true,
  'js': true,
  'jsx': true,
  'less': true,
  'scss': true,
  'wasm': true
}
